# Generated by Django 3.1.5 on 2024-11-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otheracademic', '0006_leaveformtable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveformtable',
            name='curr_sem',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='leaveformtable',
            name='leave_mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='leaveformtable',
            name='parent_mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='leaveformtable',
            name='stud_mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
